version: "3"
services:
  rso-notifications:
    image: ls8856/rso-teamlj-notifications:2.3
    ports:
    - 8085:8085
    environment:
      KUMULUZEE_DISCOVERY_ETCD_HOSTS: http://etcd:2379
    depends_on:
    - postgres
