kumuluzee:
  name: rso-notifications
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8085
    http:
      port: 8085
  #datasources:
  #  - jndi-name: jdbc/notificationsDS
  #    connection-url: jdbc:postgresql://192.168.1.5:5432/notificationTable
  #    username: dbuser
  #    password: postgres
  #    max-pool-size: 20
  discovery:
    etcd:
      hosts: http://localhost:2379
  metrics:
    web-instrumentation:
    - name: notification-endpoint
      url-pattern: /v1/notifications/*
  health:
    checks:
      disk-space-health-check:
        threshold: 100000000
  app-properties:
    external-services:
      enabled: false
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                      <Configuration name="notifications">
                          <Appenders>
                              <Console name="console" target="SYSTEM_OUT">
                                  <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                              </Console>
                              <Socket name="logstash" host="5d872f8f-f02a-4f15-b966-e8796ff99a28-ls.logit.io"
                              port="13221" protocol="tcp">
                                  <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                              </Socket>
                          </Appenders>
                          <Loggers>
                              <!-- Default logger -->
                              <Root level="all">
                                  <AppenderRef ref="console" level="info"/>
                                  <AppenderRef ref="logstash" level="trace"/>
                              </Root>
                          </Loggers>
                      </Configuration>'